<TABLE role=presentation style='BOX-SIZING: border-box; FONT-SIZE: 14px; MAX-WIDTH: 768px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 512px; WHITE-SPACE: normal; WORD-SPACING: 0px; BORDER-COLLAPSE: collapse; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(36,41,46); FONT-STYLE: normal; MARGIN-LEFT: auto; BORDER-SPACING: 0px; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); MARGIN-RIGHT: auto; font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial' cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=center>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px'>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-SIZE: 16px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; LINE-HEIGHT: 16px; PADDING-RIGHT: 0px' height=16>&nbsp;</TD></TR></TBODY></TABLE>
<TABLE style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px' cellSpacing=0 cellPadding=0 width="100%" align=left border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; TEXT-ALIGN: left !important; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=left><IMG class=CToWUd style='BORDER-TOP-STYLE: none; BOX-SIZING: border-box; BORDER-LEFT-STYLE: none; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-BOTTOM-STYLE: none; BORDER-RIGHT-STYLE: none' alt=GitHub src="https://ci3.googleusercontent.com/meips/ADKq_Nar0JIj1sLIhtrv2Pd5KMIcPWjDZmGQbwpTpIhXCr6BYNdFAyHsuPrK96vsBV08Et7bvG6-QojnCI5G9Ij2dMoHKSvMNzJaux-8V2GqOCpQ83DLLgIhw0fsvw=s0-d-e1-ft#https://github.githubassets.com/assets/octocat-logo-805b5c3e249f.png" width=32 data-bit="iit">
<H2 style='BOX-SIZING: border-box; FONT-SIZE: 24px; MARGIN-BOTTOM: 0px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; MARGIN-TOP: 8px !important; FONT-WEIGHT: 400 !important; LINE-HEIGHT: 1.25 !important'>[tawuniya20401-code/firescale-<WBR>sender] FireScale Rapid Sendmail workflow run</H2></TD></TR></TBODY></TABLE>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px'>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-SIZE: 16px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; LINE-HEIGHT: 16px; PADDING-RIGHT: 0px' height=16>&nbsp;</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE style='BOX-SIZING: border-box; FONT-SIZE: 14px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 512px; WHITE-SPACE: normal; WORD-SPACING: 0px; BORDER-COLLAPSE: collapse; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(36,41,46); FONT-STYLE: normal; BORDER-SPACING: 0px; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial' width="100%">
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; BORDER-TOP: rgb(225,228,232) 1px solid; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-RIGHT: rgb(225,228,232) 1px solid; BORDER-BOTTOM: rgb(225,228,232) 1px solid; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; BORDER-LEFT: rgb(225,228,232) 1px solid; MARGIN: 0px; DISPLAY: block !important; PADDING-RIGHT: 0px; border-radius: 6px'>
<TABLE style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 510px; BORDER-COLLAPSE: collapse; TEXT-ALIGN: center !important; BORDER-SPACING: 0px' align=center>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px'>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 510px; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px' cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=center>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 510px; BORDER-COLLAPSE: collapse; BORDER-BOTTOM: rgb(225,228,232) 1px solid; TEXT-ALIGN: center !important; BORDER-SPACING: 0px' align=center>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 16px; PADDING-LEFT: 16px; MARGIN: 0px; DISPLAY: block !important; PADDING-RIGHT: 16px'>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 478px; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px' cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=center><IMG class=CToWUd style='BORDER-TOP-STYLE: none; BOX-SIZING: border-box; BORDER-LEFT-STYLE: none; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-BOTTOM-STYLE: none; BORDER-RIGHT-STYLE: none' alt="" src="https://ci3.googleusercontent.com/meips/ADKq_NZ2FBv8eTuzPOmVLVJ7jfErYRzF0CuNaHE2CurYT_AV3uAkX4Nwy9WSDeh-l2-sBDLGnmMGNoeWni79WV1fcx2pyII1wgA8gTcSH4nuiKVEUTa0JSo=s0-d-e1-ft#https://github.githubassets.com/assets/actions-1cc0c3ccfe18.png" width=56 height=56 data-bit="iit">
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px'>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-SIZE: 12px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; LINE-HEIGHT: 12px; PADDING-RIGHT: 0px' height=12>&nbsp;</TD></TR></TBODY></TABLE>
<H3 style='BOX-SIZING: border-box; FONT-SIZE: 20px; MARGIN-BOTTOM: 0px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; MARGIN-TOP: 0px; FONT-WEIGHT: 600; LINE-HEIGHT: 1.25 !important'>FireScale Rapid Sendmail: All jobs have failed</H3>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px'>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-SIZE: 16px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; LINE-HEIGHT: 16px; PADDING-RIGHT: 0px' height=16>&nbsp;</TD></TR></TBODY></TABLE>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 478px; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px' cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=center>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px' cellSpacing=0 cellPadding=0 width="100%" border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px'>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px' cellSpacing=0 cellPadding=0 width="100%" border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=center><A style='BOX-SIZING: border-box; TEXT-DECORATION: none; BORDER-TOP: rgb(31,136,61) 1px solid; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-RIGHT: rgb(31,136,61) 1px solid; VERTICAL-ALIGN: middle; WHITE-SPACE: nowrap; BORDER-BOTTOM: rgb(31,136,61) 1px solid; FONT-WEIGHT: 500; COLOR: rgb(255,255,255); PADDING-BOTTOM: 0.75em; PADDING-TOP: 0.75em; PADDING-LEFT: 1.5em; BORDER-LEFT: rgb(31,136,61) 1px solid; DISPLAY: inline-block; LINE-HEIGHT: 1.5; PADDING-RIGHT: 1.5em; BACKGROUND-COLOR: rgb(31,136,61); border-radius: 0.5em' href="https://github.com/tawuniya20401-code/firescale-sender/actions/runs/24370576448" rel="noopener noreferrer" target=_blank data-saferedirecturl="https://www.google.com/url?q=https://github.com/tawuniya20401-code/firescale-sender/actions/runs/24370576448&amp;source=gmail&amp;ust=1776206805827000&amp;usg=AOvVaw0KS1m9MMJJdM9XzHBn9O3B">View workflow run</A></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px'>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-SIZE: 32px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; LINE-HEIGHT: 32px; PADDING-RIGHT: 0px' height=32>&nbsp;</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 510px; BORDER-COLLAPSE: collapse; TEXT-ALIGN: center !important; BORDER-SPACING: 0px' align=center>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; DISPLAY: block !important; PADDING-RIGHT: 0px'>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 510px; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px' cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=center>
<TABLE style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 510px; BORDER-COLLAPSE: collapse; TEXT-ALIGN: left !important; BORDER-SPACING: 0px'>
<THEAD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TH style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 24px; PADDING-BOTTOM: 16px; PADDING-TOP: 16px; PADDING-LEFT: 16px; PADDING-RIGHT: 0px' scope=col>Status</TH>
<TH style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 356px; PADDING-BOTTOM: 16px; PADDING-TOP: 16px; PADDING-LEFT: 16px; PADDING-RIGHT: 16px' scope=col>Job</TH>
<TH style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WHITE-SPACE: nowrap; PADDING-BOTTOM: 16px; PADDING-TOP: 16px; PADDING-LEFT: 0px; PADDING-RIGHT: 16px' scope=col>Annotations</TH></TR></THEAD>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 16px; PADDING-TOP: 16px; PADDING-LEFT: 16px; MARGIN: 0px; PADDING-RIGHT: 0px'><IMG class=CToWUd style='BORDER-TOP-STYLE: none; BOX-SIZING: border-box; BORDER-LEFT-STYLE: none; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-BOTTOM-STYLE: none; BORDER-RIGHT-STYLE: none' alt=fast-dispatch src="https://ci3.googleusercontent.com/meips/ADKq_NbWHhBS_bNRjEmnD0lFTRTpT_YpEIMYjra4VYDB9appeFbVbt_WTGDHBEM9c_caydsxNWWh_Lqh-qqo5sy-WIjBkaenQTVZrdd3uSM7nmeYD4M4QS34qW7Wh2804hxL=s0-d-e1-ft#https://github.githubassets.com/assets/x-circle-fill-red-153d16960fc8.png" width=24 height=24 data-bit="iit"></TD>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 356px; PADDING-BOTTOM: 16px; PADDING-TOP: 16px; PADDING-LEFT: 16px; MARGIN: 0px; PADDING-RIGHT: 16px'>
<P style='BOX-SIZING: border-box; MARGIN-BOTTOM: 0px !important; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; MARGIN-TOP: 0px'><B style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; FONT-WEIGHT: 600'>FireScale Rapid Sendmail</B><SPAN>&nbsp;</SPAN>/ fast-dispatch<BR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>Failed in 30 seconds</P></TD>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WHITE-SPACE: nowrap; PADDING-BOTTOM: 16px; PADDING-TOP: 16px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 16px'><A style='BOX-SIZING: border-box; TEXT-DECORATION: none; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; COLOR: rgb(3,102,214)' href="https://github.com/tawuniya20401-code/firescale-sender/actions/runs/24370576448" target=_blank data-saferedirecturl="https://www.google.com/url?q=https://github.com/tawuniya20401-code/firescale-sender/actions/runs/24370576448&amp;source=gmail&amp;ust=1776206805827000&amp;usg=AOvVaw0KS1m9MMJJdM9XzHBn9O3B"><IMG class=CToWUd style='BORDER-TOP-STYLE: none; BOX-SIZING: border-box; BORDER-LEFT-STYLE: none; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-BOTTOM-STYLE: none; BORDER-RIGHT-STYLE: none' alt="annotations for FireScale Rapid Sendmail / fast-dispatch" src="https://ci3.googleusercontent.com/meips/ADKq_NbZEAYw91hKD9HEYnjNUJ5kOPdWZvxfy-Xh7Vp3HGuJDaROkc5GKPtXrIms4kdKUhWoKYVDRrQicjnXxNrNY9e7Gq0emeXdBDOXuy9ZdpUlgHi-gFxhByZF=s0-d-e1-ft#https://github.githubassets.com/assets/report-gray-d5f2721544ee.png" width=16 height=16 data-bit="iit"><SPAN>&nbsp;</SPAN><SPAN style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; VERTICAL-ALIGN: middle !important; COLOR: rgb(106,115,125) !important; DISPLAY: table-cell !important'>2</SPAN></A></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-SIZE: 14px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 512px; WHITE-SPACE: normal; WORD-SPACING: 0px; BORDER-COLLAPSE: collapse; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(36,41,46); FONT-STYLE: normal; TEXT-ALIGN: center !important; BORDER-SPACING: 0px; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial' cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=center>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px'>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-SIZE: 16px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; LINE-HEIGHT: 16px; PADDING-RIGHT: 0px' height=16>&nbsp;</TD></TR></TBODY></TABLE>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px'>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-SIZE: 16px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; LINE-HEIGHT: 16px; PADDING-RIGHT: 0px' height=16>&nbsp;</TD></TR></TBODY></TABLE>
<P style='BOX-SIZING: border-box; FONT-SIZE: 14px !important; MARGIN-BOTTOM: 10px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; MARGIN-TOP: 0px; COLOR: rgb(106,115,125) !important'></P>
<P style='BOX-SIZING: border-box; FONT-SIZE: small; MARGIN-BOTTOM: 10px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; MARGIN-TOP: 0px; COLOR: rgb(102,102,102)'>—<BR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>You are receiving this because you are subscribed to this thread.<BR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'><A style='BOX-SIZING: border-box; TEXT-DECORATION: none; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; COLOR: rgb(3,102,214)' href="https://github.com/settings/notifications" target=_blank data-saferedirecturl="https://www.google.com/url?q=https://github.com/settings/notifications&amp;source=gmail&amp;ust=1776206805828000&amp;usg=AOvVaw1ymXyXN9G2U9cEMgK6RMxZ">Manage your GitHub Actions notifications</A></P></TD></TR></TBODY></TABLE>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-SIZE: 14px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; WIDTH: 512px; WHITE-SPACE: normal; WORD-SPACING: 0px; BORDER-COLLAPSE: collapse; TEXT-TRANSFORM: none; FONT-WEIGHT: 400; COLOR: rgb(36,41,46); FONT-STYLE: normal; TEXT-ALIGN: center !important; BORDER-SPACING: 0px; ORPHANS: 2; WIDOWS: 2; LETTER-SPACING: normal; BACKGROUND-COLOR: rgb(255,255,255); font-variant-ligatures: normal; font-variant-caps: normal; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial' cellSpacing=0 cellPadding=0 width="100%" align=center border=0>
<TBODY>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; PADDING-RIGHT: 0px' align=center>
<TABLE role=presentation style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; BORDER-COLLAPSE: collapse; BORDER-SPACING: 0px'>
<TBODY style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TR style='BOX-SIZING: border-box; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important'>
<TD style='BOX-SIZING: border-box; FONT-SIZE: 16px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; PADDING-BOTTOM: 0px; PADDING-TOP: 0px; PADDING-LEFT: 0px; MARGIN: 0px; LINE-HEIGHT: 16px; PADDING-RIGHT: 0px' height=16>&nbsp;</TD></TR></TBODY></TABLE>
<P style='BOX-SIZING: border-box; FONT-SIZE: 12px !important; MARGIN-BOTTOM: 10px; FONT-FAMILY: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji" !important; MARGIN-TOP: 0px; COLOR: rgb(106,115,125) !important'>GitHub, Inc. ・88 Colin P Kelly Jr Street ・San Francisco, CA 94107</P></TD></TR></TBODY></TABLE>
