name: FireScale Global Sender

on:
  workflow_dispatch:

jobs:
  send-emails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install System Sendmail
        # تثبيت محرك الإرسال الحقيقي داخل سيرفر مايكروسوفت
        run: |
          sudo apt-get update
          sudo apt-get install -y sendmail bsd-mailx
          sudo sendmail -bd -q15m # تشغيل المحرك في الخلفية

      - name: Install Dependencies
        run: npm install nodemailer

      - name: Run Script
        run: node send.js
